#!/usr/bin/perl

# loadbars (c) 2010 - 2013, Paul Buetow
# E-Mail: loadbars@mx.buetow.org WWW: http://loadbars.buetow.org
# For legal informations see COPYING and COPYING.FONT

use strict;
use warnings;
use v5.14;
use autodie;

use Getopt::Long;

my $lib;

BEGIN {
    if ( -d './lib/Loadbars' ) {
        $lib = 'lib';

    }
    else {
        $lib = '/usr/share/loadbars/lib';
    }
}

use lib $lib;

use Loadbars::Main;
use Loadbars::Constants;
use Loadbars::HelpDispatch;
use Loadbars::Shared;
use Loadbars::Utils;

my ( $hosts, $dispatch ) = Loadbars::HelpDispatch::create;
my $usage;

say( 'Loadbars ' . get_version . ' ' . Loadbars::Constants->COPYRIGHT );

Loadbars::Config::read;

my @hosts_extra;
push @hosts_extra, shift @ARGV while @ARGV and $ARGV[0] !~ /^-/;


GetOptions( 'help|?' => \$usage, $dispatch->('options') );

if ( defined $usage ) {
    say $dispatch->('usage');
    exit Loadbars::Constants->SUCCESS;
}

Loadbars::Main::cpu_set_showcores_re;

my @hosts = map {
    my ( $a, $b ) = split /\@/, $_;
    defined $b ? "$b:$a" : $a;
} split ',', $$hosts;

push @hosts, @hosts_extra;

if ( @hosts || defined $Loadbars::Main::C{cluster} ) {
    push @hosts, Loadbars::Config::get_cluster_hosts $C{cluster}
      if defined $C{cluster};

    system 'ssh-add'
      if $C{hasagent} == 0;
}
else {
    Loadbars::Main::say $dispatch->('usage');
    exit Loadbars::Constants->E_NOHOST;
}

# Expand a host 'hostname[08..10,13].example.com' to 
# hostname08.example.com 
# hostname09.example.com
# hostname10.example.com
# hostname13.example.com

=cut
my @expanded_hosts;

for my $host (@hosts) {
  my @expands = $host =~ /\[(.+\)\].*/g;

  k

  } else {
    push @expanded_hosts, $host;
  }
}
=cut

my @threads = Loadbars::Main::threads_create @hosts;
Loadbars::Main::loop $dispatch, @threads;

exit Loadbars::Constants->SUCCESS;

