#!/usr/bin/perl

# loadbars (c) 2010 - 2012, Dipl.-Inform. (FH) Paul Buetow
# E-Mail: loadbars@mx.buetow.org WWW: http://loadbars.buetow.org
# For legal informations see COPYING and COPYING.FONT

use strict;
use warnings;

use Getopt::Long;

use lib 'lib';

use Loadbars::Main;
use Loadbars::Constants;
use Loadbars::HelpDispatch;
use Loadbars::Shared;
use Loadbars::Utils;

sub main () {
    my ( $hosts, $dispatch ) = Loadbars::HelpDispatch::create;
    my $usage;

    say(Loadbars::Constants->VERSION . ' ' . Loadbars::Constants->COPYRIGHT);

    Loadbars::Config::read;

    GetOptions( 'help|?' => \$usage, $dispatch->('options') );

    if ( defined $usage ) {
        say $dispatch->('usage');
        exit Loadbars::Constants->SUCCESS;
    }

    Loadbars::Main::set_showcores_regexp;

    my @hosts = map {
        my ( $a, $b ) = split /\@/, $_;
        defined $b ? "$b:$a" : $a;
    } split ',', $$hosts;

    if ( @hosts || defined $Loadbars::Main::C{cluster} ) {
        push @hosts, Loadbars::Main::get_cluster_hosts $C{cluster} 
            if defined $Loadbars::Main::C{cluster};
        system 'ssh-add';

    }
    else {
        Loadbars::Main::say $dispatch->('usage');
        exit Loadbars::Constants->E_NOHOST;
    }

    my @threads = Loadbars::Main::create_threads @hosts;
    Loadbars::Main::main_loop $dispatch, @threads;

    exit Loadbars::Constants->SUCCESS;
}

main;

1;
